# Generated by Django 3.0.5 on 2020-05-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=35)),
                ('address', models.CharField(max_length=50)),
                ('mobile', models.IntegerField()),
            ],
        ),
    ]
